apiVersion: v1
kind: Template
metadata:
  name: chapel
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: chapel
    annotations:
      openshift.io/image.insecureRepository: "true"
  spec:
    dockerImageRepository: "172.30.1.1:5000/chapel/chapel:v0.1"
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 2
    labels:
      app: chapel
    name: chapel
  spec:
    replicas: 2
    selector:
      app: chapel
      deploymentconfig: chapel
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
        post:
          execNewPod:
            command:
              - /bin/bash
              - -c
              - echo "export GASNET_MASTERIP=\$MY_NODE_IP" > /home/chapel/mnt/exports && echo "export GASNET_SSH_OPTIONS=\"-p 2222\"" >> /home/chapel/mnt/exports && for pod in `oc get pods -l app=chapel|grep chapel|awk '{print $1}'`; do oc describe pod $pod |grep ^IP:|awk '{print $2}'; done|awk 'BEGIN { x="" } {x = x$1" "} END {print "export GASNET_SSH_SERVERS=\""x"\""}' >> /home/chapel/mnt/exports && echo "Hello World" && sleep 10
            containerName: chapel-executor
            volumes:
              - chapel-common
          failurePolicy: ignore
      type: Rolling
    template:
      metadata:
        labels:
          app: chapel
          deploymentconfig: chapel
      spec:
        containers:
        - env:
          - name: MY_NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          image: 172.30.1.1:5000/chapel/chapel:v0.1
          imagePullPolicy: Always
          name: chapel-executor
          ports:
          - containerPort: 22
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /home/chapel/mnt
            name: chapel-common

        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: chapel-common
          persistentVolumeClaim:
            claimName: mnt
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - chapel-executor
        from:
          kind: ImageStreamTag
          name: chapel:v0.1
          namespace: chapel
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: chapel
    name: chapel
  spec:
    ports:
    - name: 22-tcp
      port: 22
      protocol: TCP
      targetPort: 22
    selector:
      app: chapel
      deploymentconfig: chapel
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: mnt
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
